Reorganized elements in IfcRail Domain
bSI-InfraRoom/IFC-Specification pull request #128
Opened 2021-07-03 16:26 UTC by czapplitec

Added documentation for IfcRailDomain and reorganized elements by moving some of them to IfcProductExtension and IfcElectricalDomain. #122

2021-07-03 18:21 UTC, AlexBrad1eyCT requested changes
LFTM just a little bit of punctuation

2021-07-03 18:21 UTC, AlexBrad1eyCT commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/Documentation.md
> +* specific elements used in the track sub-domain, e.g. sleeper, frog, derailer, etc..
```suggestion
* specific elements used in the track sub-domain, e.g. sleeper, frog, derailer, etc.
```

2021-07-03 18:21 UTC, AlexBrad1eyCT approved these changes

2021-07-04 09:11 UTC, SergejMuhic approved these changes
Looks good. Merging

2021-07-04 09:11 UTC, merged