IfcActuator Rail Import BIMQ 2021-07-21T06:26:28.4609038Z
bSI-InfraRoom/IFC-Specification pull request #150
Opened 2021-07-21 06:43 UTC by jmirtsch

Rail properties for IfcActuator

2021-10-29 05:47 UTC, jmirtsch reviewed
Suggested changes.

2021-12-10 12:53 UTC, fhulin commented on IFC4x3/Properties/a/ActionBarMovement_3g9eB0$QrCGgwW7XmrxaeO/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="ActionBarMovement_3g9eB0QrCGgwW7XmrxaeO" Name="ActionBarMovement" UniqueId="ea2682c0-fdad-4c42-aea0-1e1c35ee4a18" PrimaryDataTyp
Done. Commmit : 23a962bd05b9764cc04293f6d2b700825df4893d

2021-12-10 12:53 UTC, fhulin commented on IFC4x3/Properties/c/Current_3zQJbuqOD69fAcKlNwK_SY/Documentation.md
> +The actual current and operable range.
I have reused existing Current. 23a962bd05b9764cc04293f6d2b700825df4893d

2021-12-10 12:53 UTC, fhulin commented on IFC4x3/Properties/i/InstallationLimit_0_Xq_kDdTAXR3cFcN9ZofG/Documentation.md
> +Installation limit of the device.
Already inside Maintenance Pset. I have erased this one.

2021-12-10 12:53 UTC, fhulin commented on IFC4x3/Properties/i/InstallationLimit_0_Xq_kDdTAXR3cFcN9ZofG/Documentation.md
> +Installation limit of the device.
23a962bd05b9764cc04293f6d2b700825df4893d

2021-12-10 12:54 UTC, fhulin commented on IFC4x3/Properties/m/MarkingRodMovement_0yycL4CG92IuVgPQIqAk$Z/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="MarkingRodMovement_0yycL4CG92IuVgPQIqAkZ" Name="MarkingRodMovement" UniqueId="3cf26544-3102-424b-87ea-65a4b42aefe3" PrimaryDataT
Agree. 23a962bd05b9764cc04293f6d2b700825df4893d

2021-12-10 12:54 UTC, fhulin commented on IFC4x3/Properties/n/NumberOfTractionPoints_1Nk$_0PhT2kBz$hK6Rfjvq/Documentation.md
> +The number of leverages or actuatrs needed to move turnouts.
Done 23a962bd05b9764cc04293f6d2b700825df4893d

2021-12-27 20:24 UTC, SergejMuhic requested changes

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/c/ControlPulseCurrent_1NbOptutP7sPdNxheUF3ur/Documentation.md
> +The current of the control pulse of the electric actuator.
```suggestion
The current of the electric actuator control pulse.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/h/HasLockInside_1vFkVHKPjAvvxUxFl0WWv7/Documentation.md
> +Indicates whether the locking is inside of the point machine (TRUE) or outside of it (FALSE).
```suggestion
Indicates whether the locking is inside  (TRUE) or outside (FALSE) of the point machine.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/l/LockingForce_0pLtPGaujDkwK16bnNbYZE/Documentation.md
> +Locking force of motor of the point machine.
```suggestion
Locking force of the point machine motor.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/m/MaximumOperatingTime_31nhczYx96JuYbkJ32Ejs4/Documentation.md
> +The maximum time the turnout has to complete the movement before the interlocking turns to out of control status.
```suggestion
The maximum duration of the turnout movement before the interlocking turns to out of control status.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/m/MinimumOperatingSpeed_0OpoQ0$Az5huboLE7511z3/Documentation.md
> +Minimum operating speed of point machine.
```suggestion
Minimum operating speed of the point machine.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfTractionPoints_1Nk$_0PhT2kBz$hK6Rfjvq/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="NumberOfTractionPoints_1Nk_0PhT2kBzhK6Rfjvq" Name="NumberOfTractionPoints" UniqueId="57bbff80-66b7-42b8-bf7f-ad419ba6de74" Prima
Seeing that this property is on actuator, is this not already possible to derive from the model?

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/t/TractionForce_1h6R3D6qz8J9tT_sZdxp1y/Documentation.md
> +Traction force of point machine in turnout conversion.
```suggestion
Traction force of the point machine in turnout conversion.
```

2021-12-27 20:24 UTC, SergejMuhic commented on IFC4x3/Properties/p/PointMachineType_0gfdQdlSPCaRPYyjTFQR6P/Documentation.md
> +Indicates the type of the railway point，different types of point allow trains to pass at different speeds。
```suggestion
Indicates the type of the railway point, different types of point allow trains to pass at different speeds.
```

2021-12-29 10:03 UTC, AlexBrad1eyCT requested changes

2021-12-29 10:03 UTC, AlexBrad1eyCT commented on IFC4x3/Properties/m/MarkingRodMovementLength_0yycL4CG92IuVgPQIqAk$Z/Documentation.md
> +The movement of the bar which indicates the turnout position.
```suggestion
The length of the movement bar which indicates the turnout position.
```

2021-12-29 10:14 UTC, AlexBrad1eyCT approved these changes
All Sorted

2021-12-29 10:53 UTC, SergejMuhic approved these changes

2021-12-29 10:53 UTC, merged