IfcSystemFurnitureElement Rail Import BIMQ 2021-07-21T07:33:18.1671031Z
bSI-InfraRoom/IFC-Specification pull request #183
Opened 2021-07-21 07:34 UTC by jmirtsch

Rail properties for IfcSystemFurnitureElement

2021-11-05 06:33 UTC, fhulin commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/PropertySets/Pset_SystemFurnitureElementTypeSubrack/DocPropertySet.xml
> +
Done. Commit : 26a84a52d1d2d5dd863865b663c2659ac68f2b7e

2021-11-12 07:17 UTC, fhulin commented on IFC4x3/Properties/o/OccupancyRate_27M6QfrA5DOx$xJQsKn0s4/Documentation.md
> +Indicates the ratio of occupied units to the total number of rack's vertical units. It is computed from the 2 other properties: NumberOfUnits and NumberOfOccupiedUnits.
I have erased OccupancyRate. Commit : bb6a5764b15b887e75d127b259399faa62eb2744

2021-11-25 14:48 UTC, larswik approved these changes

2021-12-03 07:24 UTC, SergejMuhic requested changes
Some changes requested.

2021-12-03 07:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfOccupiedUnits_1BOKOcsX1EP83zoqRMmf4n/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="NumberOfOccupiedUnits_1BOKOcsX1EP83zoqRMmf4n" Name="NumberOfOccupiedUnits" UniqueId="4b614626-da10-4e64-80fd-cb46d6c29131" Prima
Assuming this cannot be extracted from the model?

2021-12-03 07:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfSlots_3ol50yqfz8ZAv5ApU0vpo5/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="NumberOfSlots_3ol50yqfz8ZAv5ApU0vpo5" Name="NumberOfSlots" UniqueId="f2bc503c-d29f-488c-ae45-2b3780e73c85" PrimaryDataType="IfcI
Same question as above.

2021-12-03 07:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfSlots_3ol50yqfz8ZAv5ApU0vpo5/Documentation.md
> +Indicate the number of slots of the device.
```suggestion
Indicates the number of device slots.
```

2021-12-03 07:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfUnits_21W3fiATv7tvnEAOCGtP5b/Documentation.md
> +Indicate the number of vertical units.
```suggestion
Indicates the number of vertical units.
```

2021-12-03 07:24 UTC, SergejMuhic commented on IFC4x3/Properties/n/NumberOfUnits_21W3fiATv7tvnEAOCGtP5b/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="NumberOfUnits_21W3fiATv7tvnEAOCGtP5b" Name="NumberOfUnits" UniqueId="81803a6c-29de-47df-9c4e-298310dd9165" PrimaryDataType="IfcI
Same question as above.

2021-12-03 08:13 UTC, SergejMuhic approved these changes

2021-12-03 08:13 UTC, merged