Update Spatial Service Connectivity CT
bSI-InfraRoom/IFC-Specification pull request #238
Opened 2021-08-31 16:22 UTC by AlexBrad1eyCT

Fixes #215 

update of template replacing  IfcRelServicesBuildings with the  new generic form IfcReferencedInSpatialStructure

2021-08-31 17:56 UTC, pjanck requested changes
Typos :)

2021-08-31 17:56 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Service Connectivity/Documentation.md
> +A system, such as a distribution system, services a particular spatial structure, either an entire facility (and it specific subtypes e.g. buildings, bridges, roads or marine facilities, a facility p
```suggestion
A system, such as a distribution system, services a particular spatial structure, either an entire facility (and its specific subtypes e.g. buildings, bridges, roads, or marine facilities), a facility part, or a building storey, or any part of these structures.
```

Guessing the correct location of the closing parenthesis.

2021-08-31 17:56 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Service Connectivity/Documentation.md
> +The use of _IfcRelReferencedInSpatialStructure_ in this template provides the relationship across spatial and functional heirarchies allowing the spatial covererage of functional systems.
```suggestion
The use of _IfcRelReferencedInSpatialStructure_ in this template provides the relationship across spatial and functional hierarchies allowing the spatial coverage of functional systems.
```

2021-08-31 17:56 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Service Connectivity/Documentation.md
> +The system in question should be human identifyable by its _Name_ attribute.
```suggestion
The system (_IfcSystem_) in question should be human identifiable by its _Name_ attribute.
```

2021-09-07 07:58 UTC, pjanck approved these changes
lftm

2021-09-22 10:25 UTC, AlexBrad1eyCT commented
@SergejMuhic, @larswik or @TLiebich a secondary check and approval would be appreciated then this can be merged

2021-09-23 12:48 UTC, larswik approved these changes

2021-09-23 21:47 UTC, czapplitec commented
There is an issue that we have a requirement to reference an IfcGroup by an IfcSpatialElement.
Proposal 1: generalize this CT, using IfcGroup instead of IfcSystem, but then this CT needs to be renamed.
Proposal 2: define Group Reference as another CT.
@evandroAlfieri

2021-09-24 06:53 UTC, larswik commented
The way IfcSystem is defined: "composed for a common purpose or function or to provide a service" makes me think that it fits well with this template "Spatial Service Connectivity". IfcGroup as the general concept is defined as "an generalization of any arbitrary group". For that reason I would vote for Proposal 2 as a more generic template such as "Spatial Group Connectivity".

2021-09-24 14:57 UTC, evandroAlfieri commented
Indeed, since we made possible to reference IfcGroup in SS I think this should be reflected in some CT.
Also, do not forget some "constraints" we noted while testing System topic + working on storylines. See the first 3 here: https://github.com/IFCRail/IFC-Repository-Sandbox/blob/master/Schema%20constraints/Constraints.md

2021-09-28 07:23 UTC, merged