Product Linear Placement template update
bSI-InfraRoom/IFC-Specification pull request #259
Opened 2021-09-16 06:35 UTC by larswik

Fixes #233
Updated documentation (please review) and added ruleId:s for "RelativePlacement", "PlacesObject" and "LinearPositioningElement.Name" thanks to @pjanck.

2021-09-17 07:58 UTC, pjanck requested changes
Improvement proposal.

2021-09-17 07:58 UTC, pjanck commented on IFC4x3/Templates/Product Shape/Product Placement/Product Linear Placement/Documentation.md
> +A Product Linear Placement takes into account the ISO 19148 Linear referencing standard. Linear placement is defined by a position relative to a _IfcLinearPositioningElement_ (distance along and opti
```suggestion
A Product Linear Placement takes into account the ISO 19148 Linear referencing standard. Linear placement is defined by a position relative to a _IfcLinearPositioningElement_ (distance along and optionally lateral, vertical and longitudinal offsets), a horizontal reference direction, and a vertical axis direction. Each product placed with Product Linear Placement has an absolute placement on the _IfcLinearPositioningElement_._Representation_ where the _IfcLinearPositioningElement_  is typically instantiated as an IfcAlignment. Therefore, similarly to how _IfcSpatialElement_._ObjectPlacement_ sets the context for all contained elements, the _IfcLinearPositioningElement_._ObjectPlacement_ sets the context for all elements positioned on it. Consequently, each product placement that uses Product Linear Placement references the _IfcObjectPlacement_ of the _IfcLinearPositioningElement_ through _IfcLinearPlacement_._PlacementRelTo_.
```

2021-09-21 08:03 UTC, pjanck approved these changes
lftm

2021-09-22 10:23 UTC, AlexBrad1eyCT approved these changes
LFTM

2021-09-23 21:32 UTC, czapplitec approved these changes

2021-09-28 07:18 UTC, merged