Correcting Body Constraint & errors in other geometry Identifiers
bSI-InfraRoom/IFC-Specification pull request #268
Opened 2021-10-05 11:51 UTC by AlexBrad1eyCT

Fixes #252

adds missing Body representationIdentifier value constraints on child elements.
Discovered errors, inconsistancies and missing identifiers in other geometry CTs so addresses these.

I ran a local documentation generation an the updates fix the issues in the mvdXML and the diagrams

2021-10-06 03:18 UTC, jmirtsch commented
Hi Alex, how did you generate this?  Seems Unique Ids weren't assigned as "IfcLabel_0000000000000000000000" is serialized multiple times.

2021-10-06 09:36 UTC, AlexBrad1eyCT commented
@jmirtsch, I used IfcDoc ,so it must be in the object creation or serialisation. I thought it was a bit weird, but the generated mvdXML in the documentation output seemsuneffected and correct

2021-10-12 19:55 UTC, SergejMuhic reviewed
Looks good but we seem to have a problem with IfcDoc serialization in that it adds an id. Not sure why this was added, it has these tags in IfcDoc:
[IgnoreDataMember] [XmlIgnore]

@jmirtsch before merging, we have to talk about this.

2021-10-29 05:08 UTC, jmirtsch requested changes
Fix UniqueIds

2021-10-30 07:52 UTC, merged