Rule constraints referencing corrections
bSI-InfraRoom/IFC-Specification pull request #285
Opened 2021-11-03 17:19 UTC by AlexBrad1eyCT

fixed the references for sub templates in the IfcDoc representation, and othe minor corrections.

2021-11-08 10:53 UTC, AlexBrad1eyCT commented
@jmirtsch or @SergejMuhic can you review and approve this ASAP so we have a douvle check for errors and mistakes

2021-11-09 02:12 UTC, jmirtsch approved these changes
It looks ok to me, but not an easy one to manually review.  Hopefully @SergejMuhic can also review.

2021-11-09 06:52 UTC, AlexBrad1eyCT commented
@jmirtsch yeah bit of a difficult one, it all loads correctly in IfcDoc that is the main thing!

2021-11-16 10:39 UTC, pjanck requested changes
Lots of deletions and indentation changes. 

I just saw some typos and improved upon them here - did not see it necessary to open another pull request for that.

2021-11-16 10:39 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Structure/Spatial Interference/Spatial Interference With Zones/Documentation.md
>  The _Spatial Interference with Zone_ concept is an extension of the _Spatial Inteference_ concept which defines the relationship of spatial elements, such as facilities (_IfcFacility_ & specialised s
```suggestion
The _Spatial Interference with Zone_ concept is an extension of the _Spatial Interference_ concept which defines the relationship of spatial elements, such as facilities (_IfcFacility_ & specialised subtypes) or facility parts (_IfcFacilityPart_ with domain specific predefined types) that interfere or interface with other spatial elements across discipline spatial hierarchy branches, and extends the dataset with a related interference _IfcSpatialZone_ via the _IfcRelInterferesElements.InterferenceSpace_ attribute. The realizing _IfcSpatialZone_ should always have the _PredefinedType_ value set to INTERFERENCE.
```

Also, I'm unsure about the coding of the `&` in xml code.

2021-11-16 10:39 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Structure/Spatial Interference/Spatial Interference With Zones/Documentation.md
>  The addition of a realizing _ifcSpatialZone_ extends the functionality of this relationship with the following:
```suggestion
The addition of a realizing _IfcSpatialZone_ extends the functionality of this relationship with the following:
```

2021-11-18 13:04 UTC, merged