Adding IfcVoxelGrid
bSI-InfraRoom/IFC-Specification pull request #329
Opened 2021-12-12 10:13 UTC by SergejMuhic

Resolves #117 

Added:
1. `IfcVoxelGrid` definition

2021-12-12 14:25 UTC, anborr commented
Looks good. 
The only concern I have is whether `NumberOfVoxelsX `would be a better fit than `GridSizeX`.
There is a typo in the documentation of the `Voxels` attribute: "...array is one dimentional" must be become "...array is one-dimensional...".
Issue #198 was not considered, i.e. we cannot represent hierachies of Voxel Grids. This would require to have a `Child` relationship to 1..n `IfcVoxelGrid `objects
I propose to add a figure to the documentation.

2021-12-12 14:29 UTC, anborr requested changes
Looks good.
The only concern I have is whether `NumberOfVoxelsX `would be a better fit than `GridSizeX`.
There is a typo in the documentation of the `Voxels` attribute: "...array is one dimentional" must be become "...array is one-dimensional...".
Issue #198 was not considered, i.e. we cannot represent hierachies of Voxel Grids. This would require to have a `Child` relationship to 1..n `IfcVoxelGrid` objects
I propose to add a figure to the documentation.

2022-07-11 08:14 UTC, SergejMuhic commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +			<Documentation>Indication of voxels on the grid. The array is one-dimentional where values are distributed in the following order:
```suggestion
			<Documentation>Indication of voxels on the grid. The array is one-dimensional where values are distributed in the following order:
```

2022-08-10 14:05 UTC, larswik requested changes

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +		<DocAttribute Name="GridSizeX" UniqueId="1062135e-7018-4ec4-9ef7-3ca487268280" DefinedType="IfcInteger">
```suggestion
		<DocAttribute Name="NumberOfVoxelsX" UniqueId="1062135e-7018-4ec4-9ef7-3ca487268280" DefinedType="IfcInteger">
```

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +			<Documentation>Size of the voxel grid in the X axis.</Documentation>
```suggestion
			<Documentation>Number of voxels along the X axis.</Documentation>
```

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +		<DocAttribute Name="GridSizeY" UniqueId="70c30c22-0e2a-446d-8a02-31355e75c4e7" DefinedType="IfcInteger" AttributeFlags="1">
```suggestion
		<DocAttribute Name="NumberOfVoxelsY" UniqueId="70c30c22-0e2a-446d-8a02-31355e75c4e7" DefinedType="IfcInteger" AttributeFlags="1">
```

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +			<Documentation>Size of the voxel grid in the Y axis. If not given, the value from _GridSizeX_ shall be taken.</Documentation>
```suggestion
			<Documentation>Number of voxels along the Y axis. If not given, the value from _NumberOfVoxelsX_ shall be taken.</Documentation>
```

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +		<DocAttribute Name="GridSizeZ" UniqueId="bbb9efce-f6f6-4834-a122-fbef29b024bd" DefinedType="IfcInteger" AttributeFlags="1">
```suggestion
		<DocAttribute Name="NumberOfVoxelsZ" UniqueId="bbb9efce-f6f6-4834-a122-fbef29b024bd" DefinedType="IfcInteger" AttributeFlags="1">
```

2022-08-10 14:05 UTC, larswik commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
> +			<Documentation>Size of the voxel grid in the Z axis. If not given, the value from _GridSizeX_ shall be taken.</Documentation>
```suggestion
			<Documentation>NumberOf voxels along the Z axis. If not given, the value from _NumberOfVoxelsX_ shall be taken.</Documentation>
```

2022-08-12 06:28 UTC, larswik approved these changes

2022-08-12 13:30 UTC, merged