P&W Property Sets fixes
bSI-InfraRoom/IFC-Specification pull request #337
Opened 2022-01-01 13:00 UTC by AlexBrad1eyCT

P&W Property set fixes highlighted during deliverable import.

Fixes #327 
Fixes P&W responsibilities of #326

2022-01-19 13:41 UTC, AlexBrad1eyCT commented
@SergejMuhic a quick once over would be appreciated so it is double checked!

2023-02-23 16:55 UTC, SergejMuhic approved these changes

2023-02-23 17:12 UTC, pjanck approved these changes
I wonder about the `ApplicableType` correctness, but am in no position to propose any improvement / change.

2023-02-23 17:12 UTC, pjanck commented on IFC4x3/Properties/l/LoadBearingCapacityArea_2r2w0IRgj2ZPPZHhlnoADU/Documentation.md
> +Estimate or design maximum load bearing capacity of the defined surface/structure (e.g. soil stratum or planar slab). represented as a force per unit area measurement.
```suggestion
Estimate or design maximum load bearing capacity of the defined surface/structure (e.g. soil stratum or planar slab). Represented as a force per unit area measurement.
```

2023-02-24 11:05 UTC, AlexBrad1eyCT commented
For Some reason PSet_MarineVehicleCommon got changed to a QTO? but not the title, although it is full of dimensional values these are not derived values from the entities geometry (which is my opinion on what a QTO is unless this has changed...) they are the standardized design values set for each size class of marine vehicle hense PSet.

I have sorted this out for you @SergejMuhic!

2023-02-24 12:40 UTC, pjanck requested changes
Thanks for the fast response!

2023-02-24 12:40 UTC, pjanck commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcPortsAndWaterwaysDomain/PropertySets/Pset_MarineVehicleCommon/DocPropertySet.xml
> +<DocPropertySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="Pset_MarineVehicleCommon" UniqueId="ffe029d5-901e-429b-abb7-f9b61a7cf52b" ApplicableType="IfcVehicle/VEHICLEMARINE,IfcVehic
I'd remove Type's applicability.

2023-02-24 12:41 UTC, pjanck requested changes
Perhaps easier with proposing changes :)

2023-02-24 12:41 UTC, pjanck commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcPortsAndWaterwaysDomain/PropertySets/Pset_MarineVehicleCommon/DocPropertySet.xml
> +<DocPropertySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="Pset_MarineVehicleCommon" UniqueId="ffe029d5-901e-429b-abb7-f9b61a7cf52b" ApplicableType="IfcVehicle/VEHICLEMARINE,IfcVehic
```suggestion
<DocPropertySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="Pset_MarineVehicleCommon" UniqueId="ffe029d5-901e-429b-abb7-f9b61a7cf52b" ApplicableType="IfcVehicle/VEHICLEMARINE" PropertySetType="PSET_TYPEDRIVENOVERRIDE">
```

2023-02-24 14:00 UTC, SergejMuhic commented
Thanks @AlexBrad1eyCT looks ready for merging (apart from the type applicability). One thing I notices, there were 29 changed files before, now there are 16. Is this just a consequence of the merge?

2023-02-26 18:47 UTC, SergejMuhic commented
Think this one fixes #109 also.

2023-03-03 10:19 UTC, AlexBrad1eyCT commented
@SergejMuhic, yes the reduced file changes is becuase some of the corrections had been addressed in the develop branch hence the merge conflicts so merging the most recent develop reduced the change number.

I am unsure about this issue with the Type applicability? has the prevailing opinion changed around type entities and PSET_TYPEDRIVENOVERRIDE, i have always been of the view that Psets with PSET_TYPEDRIVENOVERRIDE should be connected to the type and the instance entity. have we moved to a situation that assumes the type applicability based on the instance value seems a bit woolly to be to not use explicit notation in  the standard??

2023-03-03 11:51 UTC, SergejMuhic commented
> I am unsure about this issue with the Type applicability? has the prevailing opinion changed around type entities and PSET_TYPEDRIVENOVERRIDE, i have always been of the view that Psets with PSET_TYPEDRIVENOVERRIDE should be connected to the type and the instance entity. have we moved to a situation that assumes the type applicability based on the instance value seems a bit woolly to be to not use explicit notation in the standard??

I got a response about this issue. It was said that `PSET_TYPEDRIVENOVERRIDE` would be documented only on occurrences and consequently the applicabilities followed suit.

2023-03-03 12:03 UTC, AlexBrad1eyCT commented
So Woolly it is...

2023-03-03 12:08 UTC, AlexBrad1eyCT commented
Type Applicability Applied

2023-03-12 08:23 UTC, SergejMuhic commented on IFC4x3/Properties/e/EnergySource_0yj3k0qSOHuO00025QrE$V/Documentation.md
> +Enumeration defining the energy source or fuel combusted to generate heat.
😄

2023-03-12 08:23 UTC, SergejMuhic commented on IFC4x3/PropertyEnumerations/b/PEnum_BoreholeState.xml
> +<DocPropertyEnumeration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="PEnum_BoreholeState" Name="PEnum_BoreholeState" UniqueId="84d3d099-2c7c-40b5-97f4-514b9ecd836a">
This one requires an encoded guid in id. Re-serializing with IfcDoc would probably make sense.

2023-03-14 08:42 UTC, SergejMuhic commented on IFC4x3/PropertyEnumerations/b/PEnum_BoreholeState.xml
> +<DocPropertyEnumeration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="PEnum_BoreholeState" Name="PEnum_BoreholeState" UniqueId="84d3d099-2c7c-40b5-97f4-514b9ecd836a">
I will merge and regenerate if necessary.

2023-03-14 08:42 UTC, merged