Issue#435-in-IFC4.3.x-development
bSI-InfraRoom/IFC-Specification pull request #370
Opened 2022-03-08 11:45 UTC by larswik

- Remove IfcKerb/IfcKerbType.Mountable
- Add IsMountable : IfcBoolean to Pset_KerbCommon
- PSet_KerbCommon applicability fixed (both IfcKerb and IfcKerbType)
- Added Enumeration IfcKerbTypeEnum {USERDEFINED, NOTDEFINED}
- Added PredefinedType : IfcKerbTypeEnum to IfcKerb and IfcKerbType
- Added where-rules CorrectPredefinedType and CorrectType assigned to IfcKerb
- Added where-rule CorrectPredefinedType to IfcKerbType

Fixes https://github.com/buildingSMART/IFC4.3.x-development/issues/435

2022-03-08 15:01 UTC, pjanck commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRoadDomain/Entities/IfcKerb/DocEntity.xml
> +			<Documentation>Either the _PredefinedType_ attribute is unset(e.g. because an _IfcKerbType_ is associated), or the inherited attribute _ObjectType_ shall be provided, if the _PredefinedType_ is se
```suggestion
			<Documentation>Either the _PredefinedType_ attribute is unset (e.g. because an _IfcKerbType_ is associated), or the inherited attribute _ObjectType_ shall be provided, if the _PredefinedType_ is set to USERDEFINED.</Documentation>
```

2022-03-15 09:24 UTC, SergejMuhic requested changes
Just noticed I missed this PR. 2 changes requested.

2022-03-15 09:24 UTC, SergejMuhic commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRoadDomain/Entities/IfcKerb/DocEntity.xml
> +NOTE  The PredefinedType shall only be used, if no IfcKerbType is assigned, providing its own IfcKerbType.PredefinedType.</Documentation>
```suggestion
>NOTE  The PredefinedType shall only be used, if no IfcKerbType is assigned, providing its own IfcKerbType.PredefinedType.</Documentation>
```

2022-03-15 09:24 UTC, SergejMuhic commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRoadDomain/Entities/IfcKerbType/DocEntity.xml
> +			<Documentation>The inherited attribute _ElementType_ shall be provided, if the _PredefinedType_ is set to USERDEFINED.</Documentation>
```suggestion
			<Documentation>The inherited attribute _ObjectType_ shall be provided, if the _PredefinedType_ is set to USERDEFINED.</Documentation>
```

2022-03-15 17:12 UTC, SergejMuhic approved these changes
Looks good.

2022-03-15 17:13 UTC, merged