Common improvements and documentation
bSI-InfraRoom/IFC-Specification pull request #43
Opened 2021-05-25 12:19 UTC by AlexBrad1eyCT

Documentation additions and corrections for common entities and Psets, I think i got most of them if i missed anything please let me know

2021-05-26 13:07 UTC, larswik requested changes

2021-05-26 13:07 UTC, larswik commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcTransportElementNonFixedTypeEnum/Documentation.md
> +This enumeration is used to identify **non-fixed**or **mobile** transport element types.
Maybe add a blank before "or".

2021-05-26 19:05 UTC, SergejMuhic reviewed
More than half of my comments refer to the PredefinedType description. No worries, just a suggestion to simplify. :)

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcImpactProtectionDeviceType/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a impact device from which the type modelled, may be set.</Documentation>
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcPavement/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a pavement element from which the type modelled, may be set. This type may associate additional specific property sets.
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcPavementType/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a pavement element from which the type modelled, may be set.</Documentation>
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcSign/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a signs from which the type modelled, may be set. This type may associate additional specific property sets.
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcSignType/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a signs from which the type modelled, may be set.</Documentation>
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcSignal/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a signal from which the type modelled, may be set. This type may associate additional specific property sets.
+1

2021-05-26 19:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcSignalType/DocEntity.xml
> +			<Documentation>Identifies the predefined type of a signal from which the type modelled, may be set.
+1

2021-05-27 09:26 UTC, AlexBrad1eyCT commented on IFC4x3/Constants/b/BIQUADRATICPARABOLA_14V3RUc6LFh9bZo1rEFhxL.xml
> +<DocConstant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="BIQUADRATICPARABOLA" UniqueId="447c36de-9865-4fac-9963-c81d4e3ebed5">
sorted

2021-05-27 09:27 UTC, AlexBrad1eyCT commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcTransportElementNonFixedTypeEnum/Documentation.md
> +This enumeration is used to identify **non-fixed**or **mobile** transport element types.
nice catch fixed

2021-05-27 09:29 UTC, AlexBrad1eyCT commented on IFC4x3/Constants/l/LONGITUDINAL_0k4SnEIKP3eQNUDPFSWApR.xml
> +	<Documentation>A longitidunal usage implies a subdivision along a linear facility where the part hasa defined start and end along the facility alignment(s).</Documentation>
sorted

2021-05-27 09:30 UTC, AlexBrad1eyCT commented on IFC4x3/PropertyConstants/d/DEMOLISH_1ImWWTgxn0Rx9Wgwk3G9XM.xml
> +<DocPropertyConstant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="DEMOLISH" UniqueId="52c2081d-abbc-406f-b260-abab83409856" />
sorted

2021-05-27 09:31 UTC, AlexBrad1eyCT commented on IFC4x3/PropertyConstants/e/EXISTING_0zWzHkBQH9KPgJBhLqZc5Z.xml
> +<DocPropertyConstant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="EXISTING" UniqueId="3d83d46e-2da4-4951-9a93-2eb5748e6163" />
sorted

2021-06-07 16:44 UTC, AlexBrad1eyCT commented on IFC4x3/Constants/r/REGION_1UCtBdxyD3IhR0nOLSW6Tb.xml
> +	<Documentation>A regional usage implies a bounded subdivision in the &quot;X-Y plane&quot; of a larger facility or facility part. the larger facility can be longitudinal or regional in nature.</Docu
updated to 'parent IfcSpatialStructureElement'.

2021-06-07 16:45 UTC, AlexBrad1eyCT commented on IFC4x3/PropertyConstants/n/NEW_2Mmm0WNuPEsxi1hfv0PzYn.xml
> +<DocPropertyConstant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="NEW" UniqueId="96c30020-5f86-4edb-bb01-ae9e4067d8b1" />
sorted

2021-06-07 16:45 UTC, AlexBrad1eyCT commented on IFC4x3/PropertyConstants/t/TEMPORARY_3MpsFaeAD33h8OSkOafpSq.xml
> +<DocPropertyConstant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="TEMPORARY" UniqueId="d6cf63e4-a0a3-430e-b218-72e624a73734" />
sorted

2021-06-07 17:11 UTC, AlexBrad1eyCT commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcBuiltSystem/DocEntity.xml
> +			<Documentation>Identifies the predefined type of the system from which the type modelled, may be set. This type may associate additional specific property sets.</Documentation>
sure, this is copied from the UML and originally copied from the last IFC release. i Simplifiied see new commit

2021-06-07 17:15 UTC, AlexBrad1eyCT commented
added requested changes

2021-06-08 07:39 UTC, merged