Adding IfcEarthingElement/IfcEarthingElementType as new subtypes of IfcFlowTerminal/IfcFlowTerminalType
bSI-InfraRoom/IFC-Specification pull request #430
Opened 2022-06-13 14:09 UTC by larswik

Fixes #403

2022-07-30 08:55 UTC, SergejMuhic requested changes
1. Adjusted the constant documentation to be in-line with the rest of IFC documentation
2. Could add the documentation for WRs

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Constants/g/GROUNDINGMESH_1WFsqjqs54qPDn6VzU$xcd.xml
> +	<Documentation>IEC 60050-531 An electrode in the form of a mesh, and designed to establish an equipotential plan.</Documentation>
```suggestion
	<Documentation>Definition according to IEC 60050-531: An electrode in the form of a mesh, and designed to establish an equipotential plan.</Documentation>
```

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Constants/f/FIXEDTERMINAL_3HhDuEn2f2nP6ZL0SQeoy3.xml
> +	<Documentation>According to EN 62561-2, for installation in concrete as a corrosion-free connection to the earth-termination system for protective equipotential bonding and / or functional equipoten
```suggestion
	<Documentation>Definition according to EN 62561-2: for installation in concrete as a corrosion-free connection to the earth-termination system for protective equipotential bonding and / or functional equipotential bonding of the down conductor</Documentation>
```

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Constants/e/EARTHINGSTRIP_3Fh7NdPNTF3fo7Avf2LN6_.xml
> +	<Documentation>According to EN 62561-2, for use in earth-termination and lightning protection systems as well as for ring equipotential bonding.</Documentation>
```suggestion
	<Documentation>Definition according to EN 62561-2: for use in earth-termination and lightning protection systems as well as for ring equipotential bonding.</Documentation>
```

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Constants/g/GROUNDINGPLATE_3lDZcwSjL5iAoe6FsC_G2e.xml
> +	<Documentation>IEC 62561-2 Earth electrode consisting of a metal plate buried in the ground</Documentation>
```suggestion
	<Documentation>Definition according to IEC 62561-2: Earth electrode consisting of a metal plate buried in the ground.</Documentation>
```

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Constants/g/GROUNDINGROD_25zpcaPd9AvhSIrZdgJ$rm.xml
> +	<Documentation>IEC 62561-2 Earth electrode consisting of a metal rod driven into the ground</Documentation>
```suggestion
	<Documentation>Definition according to IEC 62561-2: Earth electrode consisting of a metal rod driven into the ground.</Documentation>
```

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcElectricalDomain/Entities/IfcEarthingElementType/DocEntity.xml
> +		<DocWhereRule Name="CorrectPredefinedType" UniqueId="50650d61-371b-4e09-9af1-f9d9d2880c25">
Could add documentation for WRs.

2022-07-30 08:55 UTC, SergejMuhic commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcElectricalDomain/Entities/IfcEarthingElement/DocEntity.xml
> +			<Expression>NOT(EXISTS(PredefinedType)) OR
Documentation for WRs.

2022-08-08 12:16 UTC, larswik commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcElectricalDomain/Entities/IfcEarthingElementType/DocEntity.xml
> +		<DocWhereRule Name="CorrectPredefinedType" UniqueId="50650d61-371b-4e09-9af1-f9d9d2880c25">
Done.

2022-08-08 12:16 UTC, larswik commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcElectricalDomain/Entities/IfcEarthingElement/DocEntity.xml
> +			<Expression>NOT(EXISTS(PredefinedType)) OR
Done.

2022-08-11 21:35 UTC, anborr approved these changes

2022-08-12 13:31 UTC, SergejMuhic approved these changes

2022-08-12 13:32 UTC, merged