New PDTs for IfcBuiltSystem
bSI-InfraRoom/IFC-Specification pull request #432
Opened 2022-06-13 14:42 UTC by larswik

Fixes #401, #389

2022-07-30 08:59 UTC, SergejMuhic requested changes

2022-07-30 08:59 UTC, SergejMuhic commented on IFC4x3/Constants/f/FIREPROTECTION_2Z7j5jACn9tOoK92Pdiwhi.xml
> +	<Documentation>Passive fire protection for containing the fire and preventing it from spreading further.</Documentation>
```suggestion
	<Documentation>Passive fire protection for containing fire and preventing it from spreading further.</Documentation>
```

2022-07-30 08:59 UTC, SergejMuhic commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcBuiltSystemTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="TUNNEL_PRESUPPORT_3A1ZcrqfEERtMff4Wx0wB" />
Should be moved above USERDEFINED.

2022-08-08 12:01 UTC, larswik commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcBuiltSystemTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="TUNNEL_PRESUPPORT_3A1ZcrqfEERtMff4Wx0wB" />
Done.

2022-08-11 14:31 UTC, SergejMuhic approved these changes

2022-08-11 21:32 UTC, anborr approved these changes

2022-08-12 13:43 UTC, SergejMuhic approved these changes

2022-08-12 13:44 UTC, merged