New PDTs for IfcElementAssembly
bSI-InfraRoom/IFC-Specification pull request #433
Opened 2022-06-13 14:52 UTC by larswik

Fixes #400 
DUCTBANK and UMRELLAVAULT

2022-07-30 09:01 UTC, SergejMuhic requested changes

2022-07-30 09:01 UTC, SergejMuhic commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcElementAssemblyTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="DUCTBANK_2gyrzas65BMhu1elkYUn1T" />
Move above USERDEFINED.

2022-08-08 11:53 UTC, larswik commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcElementAssemblyTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="DUCTBANK_2gyrzas65BMhu1elkYUn1T" />
Done.

2022-08-11 14:34 UTC, SergejMuhic approved these changes

2022-08-11 21:30 UTC, anborr approved these changes

2022-08-12 14:40 UTC, merged