Add IfcProductData
bSI-InfraRoom/IFC-Specification pull request #440
Opened 2022-06-16 06:57 UTC by larswik

In schema IfcProductExtension.
Fixes #439 .

2022-06-20 13:58 UTC, anborr requested changes
After checking the other subtypes of IfcProduct, I would prefer IfcDataElement.

2022-06-20 18:42 UTC, SergejMuhic commented
> After checking the other subtypes of IfcProduct, I would prefer IfcDataElement.

IfcData maybe. Having difficulties wrapping my head around what a data element would be.

2022-06-21 08:30 UTC, larswik commented
> > After checking the other subtypes of IfcProduct, I would prefer IfcDataElement.
> 
> IfcData maybe. Having difficulties wrapping my head around what a data element would be.

I can see that IfcProductData may lead the "product data templates" people in the wrong direction. However, "IfcData" feels very vague and generic, as does "IfcDataElement". What we want to achieve is an element that, besides having its own properties and possibly representations, should always be associated with another IfcProduct. Also, in IFC, a product is not restricted to items sold by manufacturers. One alternative, if we can't agree on a generic term, would be to have IfcObservation as a separate thing directly under IfcProduct and make IfcVoxelData a separate, rooted or non-rooted, thing which may mean that IfcVoxelData would again need a separate relationship to the product it describes. My take is that "IfcProductData" is the best alternative yet (it is "just" a term which no end-user will ever have to see). How about "IfcProductRelatedData"? "My kingdom for a term"!

2022-06-23 13:02 UTC, SergejMuhic commented
What else to add. When I proposed the name it seemed a natural extension of the IfcProduct entity. I never felt any connection to anything other than that. Anything beyond, is not my domain. I am therefore completely fine with IfcProductData.

2022-06-23 15:40 UTC, anborr commented
I am really afraid that we see ourselves run into unnecessary trouble when we use "Product Data" as most people in AEC will associate this with Manufacturer Sheets etc. 
Also, from a pure "terminology science" point of view, the more abstract term must always come at the end of the more precise term: "Car" -> "RacingCar". This would result in "IfcDataProduct" which might be fine. At the same time, some subtypes of `IfcProduct` have the ending "..element", such as `IfcSpatialElement`, `IfcLinearElement` and `IfcPositioningElement`, so `IfcDataElement` seemed to be a natural candidate... In the end, the thing we describe here is an element of the model, right? 
But we also have "..Item" in `IfcStructuralItem`. So what about `IfcDataItem`?

2022-06-27 16:01 UTC, larswik commented
IfcComplementaryData

2022-06-28 06:26 UTC, larswik commented
Changed name IfcProductData=>IfcComplementaryData. Great if this PR could be handled quickly since there are other dependent PR waiting to happen (IfcVoxelData & IfcGeoScienceObservation). Ping @SergejMuhic & @anborr .

2022-06-30 07:37 UTC, SergejMuhic approved these changes

2022-06-30 07:37 UTC, SergejMuhic commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcComplementaryData/Documentation.md
> +A kind of product with the purpose of providing additional information, such as observations,  to other products. Complementary data may carry its own representation and shall be related to the main
```suggestion
A kind of product with the purpose of providing additional raw data, such as observations,  to other products. Complementary data may carry its own representation and shall be related to the main product using _IfcRelAssignsToProduct_.
```

2022-06-30 07:38 UTC, merged