Add IfcPlate/LAGGING
bSI-InfraRoom/IFC-Specification pull request #441
Opened 2022-06-16 08:37 UTC by larswik

Fixes #390

2022-07-30 09:05 UTC, SergejMuhic requested changes

2022-07-30 09:05 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Types/IfcPlateTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="LAGGING_0ktjQG6av2Gv8cg1n6O0K0" />
Move above USERDEFINED.

2022-08-08 11:29 UTC, larswik commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Types/IfcPlateTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="LAGGING_0ktjQG6av2Gv8cg1n6O0K0" />
Done.

2022-08-11 21:21 UTC, anborr approved these changes

2022-08-12 15:36 UTC, SergejMuhic approved these changes

2022-08-12 15:36 UTC, merged