IfcDiscreteAccessory PDTs
bSI-InfraRoom/IFC-Specification pull request #442
Opened 2022-06-16 09:29 UTC by larswik

Fixes #388

2022-07-30 09:06 UTC, SergejMuhic requested changes

2022-07-30 09:06 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedComponentElements/Types/IfcDiscreteAccessoryTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="WATER_BARRIER_0os3AKyc13t9bGOSSUjaAG" />
Move above USERDEFINED.

2022-08-08 11:25 UTC, larswik commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedComponentElements/Types/IfcDiscreteAccessoryTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="WATER_BARRIER_0os3AKyc13t9bGOSSUjaAG" />
Done.

2022-08-11 21:19 UTC, anborr approved these changes

2022-08-12 15:37 UTC, SergejMuhic approved these changes

2022-08-12 15:37 UTC, merged