IfcSpatialZone PDTs added
bSI-InfraRoom/IFC-Specification pull request #443
Opened 2022-06-16 14:29 UTC by larswik

Fixes #387.
Definitions needs to be reviewed and maybe generalized!

2022-07-30 09:21 UTC, SergejMuhic requested changes

2022-07-30 09:21 UTC, SergejMuhic commented on IFC4x3/Constants/i/INVERT_3ak1q6i1jEY9NYIl0zD_62.xml
> +	<Documentation>The lowest section of a tunnel (floor space)</Documentation>
```suggestion
	<Documentation>The lowest section of a tunnel (floor space).</Documentation>
```

2022-07-30 09:21 UTC, SergejMuhic commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcSpatialZoneTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="MAPPEDZONE_0jgnCtnpD0JQYvromoT_1" />
Move above USERDEFINED.

2022-08-08 11:19 UTC, larswik commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcSpatialZoneTypeEnum/DocEnumeration.xml
> +		<DocConstant xsi:nil="true" href="MAPPEDZONE_0jgnCtnpD0JQYvromoT_1" />
Done.

2022-08-11 21:00 UTC, anborr requested changes

2022-08-11 21:00 UTC, anborr commented on IFC4x3/Constants/c/CLEARANCE_2WTa08IAn2wQFVvRSpIrPs.xml
> +	<Documentation>The space required for the safe operation of vehicles such as a locomotive along a fixed track,</Documentation>
```suggestion
	<Documentation>The space required for the safe operation of vehicles such as trains along a fixed track.</Documentation>
```

2022-08-12 15:38 UTC, SergejMuhic approved these changes

2022-08-12 15:39 UTC, SergejMuhic commented
Looks as though @anborr comments were addressed.

2022-08-12 15:39 UTC, merged