Adding IfcVoxelData and subclasses
bSI-InfraRoom/IFC-Specification pull request #458
Opened 2022-06-30 09:29 UTC by larswik

Fixes #448

2022-07-26 13:07 UTC, anborr reviewed
For naming consistency, I propose to use ...Data instead of ..Values for all subtypes of IfcVoxelData.

E.g., IfcIntegerVoxelValues would then become IfcIntegerVoxelData.

2022-07-30 09:56 UTC, SergejMuhic approved these changes
Looks good to me.

2022-08-01 15:55 UTC, anborr requested changes
For naming consistency, I would prefer to use IfcVoxelxxxData instead of IfcVoxelxxxValues for all subtypes of IfcVoxelData. E.g., IfcIntegerVoxelValues would then become IfcIntegerVoxelData.

The rest is approved.

2022-08-08 08:58 UTC, larswik commented
Should now be ok with regards to comments.

2022-08-11 20:54 UTC, anborr approved these changes

2022-08-12 10:11 UTC, larswik commented
An optional Unit : IfcUnit should be added to IfcVectorVoxelData.

2022-08-12 10:17 UTC, larswik commented
> An optional Unit : IfcUnit should be added to IfcVectorVoxelData.

Fixed in [e8d311e](https://github.com/bSI-InfraRoom/IFC-Specification/pull/458/commits/e8d311e3a638fa64ea7ce1b4d4b0a184b62f7e28)

2022-08-12 11:31 UTC, SergejMuhic commented on IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcVectorVoxelData/DocEntity.xml
> +			<Documentation>An optional unit for the vector values.</Documentation>
```suggestion
			<Documentation>An optional unit for the vector values that overrides the default Magnitude IfcLengthMeasure.</Documentation>
```

2022-08-12 11:39 UTC, SergejMuhic approved these changes

2022-08-12 11:39 UTC, merged