Feature/property normalization
bSI-InfraRoom/IFC-Specification pull request #467
Opened 2022-07-29 07:50 UTC by SergejMuhic

I guess the name of this issue is not perfect 😄 but trying to keep the reference.

1. Rename IfcWorkTime.Start/Finish to StartDate/FinishDate
2. Change type IfcSweptDiskSolidPolygonal.FilletRadius to IfcNonNegativeLengthMeausure -> I cannot say I understand this change, especially with the description in place "The fillet that is equally applied to all transitions between the segments of the [IfcPolyline](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPolyline.htm), providing the geometric representation for the Directrix. **If omitted, no fillet is applied to the segments**." What does FilletRadius = 0 compared to omitted mean?
3. Rename IfcStructuralCurveConnection.Axis to AxisDirection
4. Rename IfcClassification.Location to Specification
5. IfcIndexedPolyCurve.SelfIntersect mandatory and type to IfcLogical -> was this necessary? Again, especially with the description in place "Indication of whether the curve intersects itself or not; **this is for information only**."
6. Rename IfcMaterialRelationship.Expression to MaterialExpression
7. Rename IfcCurveStyleFontAndScaling.CurveFont to CurveStyleFont
8. Update of rule Name to reflect IfcClassification.Location name change

2022-07-29 17:55 UTC, TLiebich commented
to 2.) agree, in this context being optional - meaning no radius (=0) and allowing radius=0 (i.e. having to options for the same) is not a semantic improvement - @aothms - revert that change?

to 5) we discussed it also in the ISO group and defended the change - see http://ifc43-docs.standards.buildingsmart.org/search?query=selfintersect - all other SelfIntersect attributes are mandatory logicals

2022-07-30 14:30 UTC, SergejMuhic commented
> to 2.) agree, in this context being optional - meaning no radius (=0) and allowing radius=0 (i.e. having to options for the same) is not a semantic improvement - @aothms - revert that change?
> 
> to 5) we discussed it also in the ISO group and defended the change - see http://ifc43-docs.standards.buildingsmart.org/search?query=selfintersect - all other SelfIntersect attributes are mandatory logicals

On 5. it would make sense to adjust the documentation then. Might I propose "Indication of whether the curve intersects itself or not; this is for information only. UNKNOWN shall be used also in exchanges where this information is deemed irrelevant."

2022-08-04 13:45 UTC, SergejMuhic commented
`IfcIndexedPolyline` was reverted.

2022-08-26 12:57 UTC, aothms commented
2.

It's a unification of all FilletRadius types, e.g IfcIShapeProfileDef.FilletRadius which is also OPTIONAL IfcNonNegativeLengthMeasure.

The description there is

> The fillet between the web and the flange. 0 if sharp-edged, omitted if unknown.

I would propose to keep the unification and reword the documentation to:

> The fillet that is equally applied to all transitions between the segments of the Directrix. 0 if sharp-edged, omitted if unknown.

In that I also removed IfcPolyline because it can also be an IfcIndexedPolyCurve

2022-08-27 18:04 UTC, SergejMuhic commented
If the backwards compatibility rules are okay with this change, then I see no problems. The documentation change also works fine apart from removing `IfcPolyline` which is quite necessary 😄.

2023-02-09 18:25 UTC, SergejMuhic commented
@aothms @TLiebich It seems to me that the IfcSweptDiskSolidPolygonal was just changed to OPTIONAL and the documentation has not changed. Must have been submitted to ISO like that then.



> It's a unification

On this I would have expected the unification to go the other way around honestly. From a more common entity to the one that is less used.

Are there plans on changing the documentation? I was waiting with this PR for that but now I would have to merge for Tunnel Deployment to have a solid baseline.

2023-03-03 21:10 UTC, pjanck requested changes

2023-03-03 21:10 UTC, pjanck commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralAnalysisDomain/Entities/IfcStructuralCurveConnection/DocEntity.xml
>  			<Documentation>Direction which is used in the definition of the local z axis.  _Axis_ is specified relative to the so-called global coordinate system, i.e. the _SELF\IfcProduct.ObjectPlacement_.
```suggestion
		<DocAttribute Name="AxisDirection" UniqueId="7ab9edfa-dde7-4c6c-8c6a-ce1cd8fc527c" DefinedType="IfcDirection" XsdFormat="attribute">
			<Documentation>Direction which is used in the definition of the local z axis.  _AxisDirection_ is specified relative to the so-called global coordinate system, i.e. the _SELF\IfcProduct.ObjectPlacement_.
```

Let's correct the documentation as well, if the attribute name got changed.

2023-03-03 21:10 UTC, pjanck commented on IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralAnalysisDomain/Entities/IfcStructuralCurveConnection/DocEntity.xml
>  &gt; NOTE&amp;nbsp; It is desirable and usually possible that many instances of _IfcStructuralCurveConnection_ and _IfcStructuralCurveMember_ share a common instance of _IfcDirection_ as their _Axis_
```suggestion
&gt; NOTE&amp;nbsp; It is desirable and usually possible that many instances of _IfcStructuralCurveConnection_ and _IfcStructuralCurveMember_ share a common instance of _IfcDirection_ as their _AxisDirection_ attribute.</Documentation>
```

Simile.

2023-03-03 21:10 UTC, pjanck commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcSweptDiskSolidPolygonal/DocEntity.xml
>  			<Documentation>The fillet that is equally applied to all transitions between the segments of the _IfcPolyline_, providing the geometric representation for _the Directrix_. If omited, no fillet is
```suggestion
			<Documentation>The fillet that is equally applied to all transitions between the segments of the _IfcPolyline_, providing the geometric representation for the _Directrix_. If omitted, no fillet is applied to the segments.</Documentation>
```

2024-06-07 08:20 UTC, larswik commented
Suggest to merge and derive an issue both here and in the official repository regarding the fillet radius.

2024-06-07 08:23 UTC, larswik approved these changes

2024-06-07 14:13 UTC, merged