Feature/polygonal faceset texture
bSI-InfraRoom/IFC-Specification pull request #470
Opened 2022-07-29 09:08 UTC by SergejMuhic

1. Added IfcTextureCoordinateIndices and documentation
2. Adding IfcTextureCoordinateIndicesWithVoids and documentation
3. Adding attribute IfcIndexedPolygonalFace.HasTexCoords
4. Added schema references

2023-01-16 16:33 UTC, pjanck requested changes
Two typos, otherwise seems fine.

2023-01-16 16:33 UTC, pjanck commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcPresentationAppearanceResource/Entities/IfcTextureCoordinateIndices/Documentation.md
> +The _IfcTextureCoordinateIndices_ provide the texture coordinates for an _IfcIndexedPolygonalFace_. The _TexCoordIndex_ holds a list of indices pointing into the _IfcTextureVertexList_ for texture co
```suggestion
The _IfcTextureCoordinateIndices_ provide the texture coordinates for an _IfcIndexedPolygonalFace_. The _TexCoordIndex_ holds a list of indices pointing into the _IfcTextureVertexList_ for texture coordinates that correspond to the _TexCoordsOf.CoordIndex_ holding a list of indices pointing into the _IfcCartesianPointList3D_ for vertex coordinates.
```

2023-01-16 16:33 UTC, pjanck commented on IFC4x3/Sections/Resource definition data schemas/Schemas/IfcPresentationAppearanceResource/Entities/IfcTextureCoordinateIndicesWithVoids/Documentation.md
> +- the second dimension corresponds to the list position of the vertices at the nth inner loop at _IfcIndexedPolygonalFaceWithVoids_
```suggestion
- the second dimension corresponds to the list position of the vertices at the n-th inner loop at _IfcIndexedPolygonalFaceWithVoids_
```

2023-02-01 19:24 UTC, SergejMuhic commented
Ping @jmirtsch @peterrdf @larswik @anborr @TLiebich @czapplitec one more review please. Thanks.

2023-02-01 22:11 UTC, pjanck approved these changes
lftm

2023-02-02 10:05 UTC, TLiebich approved these changes
looks fine

2023-02-08 19:37 UTC, merged