Pset_BuiltSystemTypeWaterproofing
bSI-InfraRoom/IFC-Specification pull request #573
Opened 2023-04-17 06:53 UTC by larswik

# Pset: Pset_BuiltSystemTypeWaterproofing

## Applicability: IfcBuiltSystem/WATERPROOFING

## Description: 

Properties for waterproofing systems

| Property                     | Datatype                  | Description                                 |
| ---------------------------- | ------------------------- | ------------------------------------------- |
| WaterproofingSystem          | PEnum_WaterproofingSystem | Indicates the type of waterproofing system  |
| WatertightnessClassification | IfcLabel                  | Specifies the watertightness classification |

## Enumeration: PEnum_WaterproofingSystem

| Constant   | Description |
| ---------- | ----------- |
| WATERTIGHT |             |
| DRAINED    |             |

2023-06-25 07:21 UTC, SergejMuhic commented
No descriptions for constants.

2023-06-30 14:54 UTC, JontyDunn commented
WATERTIGHT The groundwater water is prevented from penetrating the tunnel. The full water pressure acts on the tunnel lining

DRAINED  The groundwater flows freely through a drainage layer into the tunnel and is collected with a seepage pipe.  A reduced water pressure acts on the tunnel lining

2023-07-08 14:35 UTC, SergejMuhic requested changes

2023-07-08 14:35 UTC, SergejMuhic commented on IFC4x3/Properties/w/WatertightnessClassification_3o5MfIEcL6VubC3CVWfHTs/DocProperty.xml
Classification references should be modeled with `IfcClassificationReference`.

2023-07-08 14:35 UTC, SergejMuhic commented on IFC4x3/PropertyEnumerations/w/PEnum_WaterproofingSystem.xml
Would be nice to have a short description for the enum.

2023-07-13 17:07 UTC, SergejMuhic commented
@michel-rives add UNKNOWN?

2023-07-13 17:44 UTC, Michel-Rives commented
> @Michel-Rives add NOTKNOWN?

Yes

2023-08-06 09:58 UTC, SergejMuhic commented
> > @Michel-Rives add NOTKNOWN?
> 
> Yes

Added.

2023-08-06 09:58 UTC, SergejMuhic approved these changes

2023-08-06 09:58 UTC, merged