BookA-Pset_GeoObsBoreholeGeophysicalInterval
bSI-InfraRoom/IFC-Specification pull request #583
Opened 2023-04-20 13:55 UTC by larswik

# Pset: Pset_GeoObsBoreholeGeophysicalInterval

## Applicability: IfcGeoScienceObservation/BOREHOLELOG

## Description: 

Properties for describing geopysical intervals

| Property | Datatype | Description |
|----------|----------|-------------|
|PwaveVelocity| According to existing definition | According to existing definition |
|SwaveVelocity| According to existing definition | According to existing definition |
|Emodulus|IfcModulusOfElasticityMeasure|"The elastic modulus (E-modulus) is a measure of the ground stiffness, describing the extent to which a material resists deformation in response to an applied force. It is defined as the ratio of the stress along an axis to the strain along that axis in the range of elastic behaviour. This property can be measured directly or derived with correlations from many different types of laboratory and in-situ test methods and is used in constitutive models for soil and rock. Many alternative and corresponding parameters describe the ground stiffness, including elastic and plastic behaviour and depending on strain (non-linear behavior), loading/unloading conditions, dynamic/static conditions, drained/undrained conditions. Such specific parameters can be defined in IFC models with custom property sets depending on the exchange scenario (e.g. for specific test results or geomechanical properties of interpreted models and materials)."|
|PoissonRatio|IfcRatioMeasure|Ratio between radial/horizontal strain and axial strain of a (geo)material when compressed.|
|BulkDensity|IfcMassDensityMeasure|The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of the grains or crystals plus the void (pore) space. The density can be dry if the pore space is empty, or it can be saturated if the pores are filled with fluid (e.g., water), which is more typical of the subsurface (in situ) situation. |
|Resistivity| According to existing definition | According to existing definition |
|SpontaneousPotential|IfcElectricVoltageMeasure|Naturally occurring (static) electrical potential in the Earth. Spontaneous potentials are usually caused by charge separation in clay or other minerals, by the presence of a semipermeable interface impeding the diffusion of ions through the pore space of rocks, or by natural flow of a conducting fluid (salty water) through the rocks. Variations in SP can be measured in the field and in wellbores to determine variations of ionic concentration in pore fluids of rocks.|
|GroundWaterTemperature|IfcThermodynamicTemperatureMeasure|Groundwater temperature obtained by a tempereature logging|
|HoleDiameter|IfcPositiveLengthMeasure|Drilled Borehole diameter (mm)|
|GammaRay|IfcReal|Naturally occurring gamma radiation which characterizes the rock or sediment in a borehole or drill hole, measured by a gamma ray logging.|

2023-11-26 18:48 UTC, SergejMuhic requested changes

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/b/BulkDensity_0nEw_cmQP96hsnDkHk7anm/Documentation.md
> +The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of t
What does "?B" mean?
This is also odd "(e.g., water)".
"The density can be dry if the pore space is empty, or it can be saturated if the pores are filled with fluid" -> this does not make sense since the WG does not consider the weight (mass?) of water.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/b/BulkDensity_0nEw_cmQP96hsnDkHk7anm/Documentation.md
> +The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of t
```suggestion
The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of the grains or crystals plus the void (pore) space. The density can be dry if the pore space is empty, or it can be saturated if the pores are filled with fluid (e.g., water) which is more typical of the subsurface (in situ) situation. 
```

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/e/Emodulus_0Tfz4hnAXCMOBE9sK0qAiG/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
`YoungModulus`? I would re-use.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/g/GammaRay_0uQOo2p7L7gfdVTXwVzLwb/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="GammaRay_0uQOo2p7L7gfdVTXwVzLwb" Name="GammaRay" UniqueId="38698c82-cc75-47aa-99df-761e9ff55ea5" PrimaryDataType="IfcReal" />
`IfcReal`?

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/g/GroundWaterTemperature_1$VLyCC_rAj9xz37v0OTla/Documentation.md
> +Groundwater temperature obtained by a tempereature logging.
I would like to correct this but I do not understand what it means.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/h/HoleDiameter_2CRBoJG6P9xwWyupBQZ76M/Documentation.md
> +Drilled Borehole diameter.
```suggestion
Drilled borehole diameter.
```

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/h/HoleDiameter_2CRBoJG6P9xwWyupBQZ76M/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Probably doesn't make sense to have it here also.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/g/GroundWaterTemperature_1$VLyCC_rAj9xz37v0OTla/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
I think I have seen this somewhere.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/p/PoissonRatio_2y5cHUFyL0rhO1Q97aJWbg/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="PoissonRatio_2y5cHUFyL0rhO1Q97aJWbg" Name="PoissonRatio" UniqueId="bc16645e-3fc5-40d6-b601-6891e44e096a" PrimaryDataType="IfcRat
Propose re-using `PoissonRatio`.

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Properties/s/SpontaneousPotential_0QWHw4BW90SxlAkUg4JefW/Documentation.md
> +Naturally occurring (static) electrical potential in the Earth. Spontaneous potentials are usually caused by charge separation in clay or other minerals, by the presence of a semipermeable interface
```suggestion
Naturally occurring (static) electrical potential in the Earth. Spontaneous potentials (SP) are usually caused by charge separation in clay or other minerals, by the presence of a semipermeable interface impeding the diffusion of ions through the pore space of rocks, or by natural flow of a conducting fluid (salty water) through the rocks. Variations in SP can be measured in the field and in wellbores to determine variations of ionic concentration in pore fluids of rocks.
```

2023-11-26 18:48 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_GeoObsBoreholeGeophysicalInterval/Documentation.md
> +Properties for describing geopysical intervals.
```suggestion
Properties for describing geophysical intervals.
```

2023-12-18 12:57 UTC, larswik commented on IFC4x3/Properties/b/BulkDensity_0nEw_cmQP96hsnDkHk7anm/Documentation.md
> +The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of t
Changed to DryBulkDensity with description "Ratio of the mass of solid to the unit total volume (dry material)." and WetBulkDensity with description "Ratio of the total mass to the unit total volume (material at its natural moisture content)." (from Pset_GeoScienceProperties - see #632 which needs to be synced with this)

2023-12-18 12:58 UTC, larswik commented on IFC4x3/Properties/b/BulkDensity_0nEw_cmQP96hsnDkHk7anm/Documentation.md
> +The bulk density of a rock is ?B = WG/VB, where WG is the weight of grains (sedimentary rocks) or crystals (igneous and metamorphic rocks) and natural cements, if any, and VB is the total volume of t
See previous comment.

2023-12-18 12:59 UTC, larswik commented on IFC4x3/Properties/e/Emodulus_0Tfz4hnAXCMOBE9sK0qAiG/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Re-used in [653d69b](https://github.com/bSI-InfraRoom/IFC-Specification/pull/583/commits/653d69bb071ec1b43b5e0983bba3cee875cd0342)

2023-12-18 12:59 UTC, larswik commented on IFC4x3/Properties/g/GroundWaterTemperature_1$VLyCC_rAj9xz37v0OTla/Documentation.md
> +Groundwater temperature obtained by a tempereature logging.
Re-used definition in [653d69b](https://github.com/bSI-InfraRoom/IFC-Specification/pull/583/commits/653d69bb071ec1b43b5e0983bba3cee875cd0342)

2023-12-18 13:01 UTC, larswik commented on IFC4x3/Properties/g/GroundWaterTemperature_1$VLyCC_rAj9xz37v0OTla/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Re-used from Pset_GeoAspects in [653d69b](https://github.com/bSI-InfraRoom/IFC-Specification/pull/583/commits/653d69bb071ec1b43b5e0983bba3cee875cd0342)
- Pset_GeoAspects (merged)
- Pset_GeoObsPtObservationCommon (merged - used the same as Pset_GeoAspects in the referenced commit)
-Pset_GeoSciencePropertiesCommon (not merged - #632). After this PR:s have been merged, this one can be synced and the extra GroundwaterTemperature be deleted.

2023-12-18 13:02 UTC, larswik commented on IFC4x3/Properties/p/PoissonRatio_2y5cHUFyL0rhO1Q97aJWbg/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="PoissonRatio_2y5cHUFyL0rhO1Q97aJWbg" Name="PoissonRatio" UniqueId="bc16645e-3fc5-40d6-b601-6891e44e096a" PrimaryDataType="IfcRat
Re-used in [653d69b](https://github.com/bSI-InfraRoom/IFC-Specification/pull/583/commits/653d69bb071ec1b43b5e0983bba3cee875cd0342)

2023-12-18 15:14 UTC, larswik commented on IFC4x3/Properties/g/GammaRay_0uQOo2p7L7gfdVTXwVzLwb/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="GammaRay_0uQOo2p7L7gfdVTXwVzLwb" Name="GammaRay" UniqueId="38698c82-cc75-47aa-99df-761e9ff55ea5" PrimaryDataType="IfcReal" />
@j-weil: Which measure/unit?

2024-05-27 07:01 UTC, larswik commented on IFC4x3/Properties/g/GammaRay_0uQOo2p7L7gfdVTXwVzLwb/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="GammaRay_0uQOo2p7L7gfdVTXwVzLwb" Name="GammaRay" UniqueId="38698c82-cc75-47aa-99df-761e9ff55ea5" PrimaryDataType="IfcReal" />
Not changed.

2024-05-27 07:02 UTC, larswik commented on IFC4x3/Properties/h/HoleDiameter_2CRBoJG6P9xwWyupBQZ76M/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Kept and added sentence to definition according to domain proposal.

2024-05-27 07:02 UTC, larswik commented on IFC4x3/Properties/g/GroundWaterTemperature_1$VLyCC_rAj9xz37v0OTla/DocProperty.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Kept the property here.

2024-05-31 09:39 UTC, SergejMuhic commented on IFC4x3/Properties/d/DryBulkDensity_0nEw_cmQP96hsnDkHk7anm/Documentation.md
> +Ratio of the mass of solid to the unit total volume (dry material).
```suggestion
Ratio of the mass of the solid to the unit total volume (dry material).
```

2024-05-31 09:47 UTC, SergejMuhic approved these changes

2024-05-31 09:48 UTC, merged