BookA-GeophysicalSurveyBorehole
bSI-InfraRoom/IFC-Specification pull request #605
Opened 2023-04-25 09:43 UTC by larswik

# Pset: Pset_GeophysicalSurveyBorehole

## Applicability: IfcGeoScienceObservation/GEOPHYSICALSURVEYRESULT

## Description: 

Properties for geophysical surveys in boreholes

| Property | Datatype | Description |
|----------|----------|-------------|
|BoreholeGeophysConfiguration|IfcLabel|Configuration of the sources and receivers used in the  borehole geophysical surveys.|

2023-05-04 08:56 UTC, patmclarin commented
please update the Pset description to: Properties for setup of geophysical surveys incorporating boreholes

2023-12-03 17:19 UTC, SergejMuhic requested changes

2023-12-03 17:19 UTC, SergejMuhic commented on IFC4x3/Properties/b/BoreholeGeophysConfiguration_1LBvY6mqnA6Bh1tDfqA$ws/Documentation.md
> +Configuration of the sources and receivers used in the  borehole geophysical surveys.
```suggestion
Configuration of the sources and receivers used in the borehole geophysical surveys.
```

2023-12-03 17:20 UTC, SergejMuhic approved these changes

2023-12-03 17:20 UTC, merged