BookB-Pset_GeoScienceFeatureTypeDiscontinuity
bSI-InfraRoom/IFC-Specification pull request #616
Opened 2023-04-28 11:45 UTC by larswik

2023-05-04 06:56 UTC, j-weil commented
Geo Domain team: Please change description as follows:
Properties of discontinuities or discontiuity sets in rock according to ISO EN 14689.

2023-05-04 06:58 UTC, larswik commented
> Geo Domain team: Please change description as follows: Properties of discontinuities or discontiuity sets in rock according to ISO EN 14689.

I can take care of that here in the PR.

2023-05-04 07:04 UTC, j-weil commented
We further need to change the property names with abbreviation "disc"... to "discontinuity"..., for consistency

2023-05-04 07:06 UTC, j-weil commented
Great, that means we do not need to make changes in the excel sheets but only leave comments in the PRs?

Von: larswik ***@***.***>
Gesendet: Donnerstag, 4. Mai 2023 08:59 Uhr
An: bSI-InfraRoom/IFC-Specification ***@***.***>
Cc: Jonas WEIL ***@***.***>; Comment ***@***.***>
Betreff: Re: [bSI-InfraRoom/IFC-Specification] BookB-Pset_GeoScienceFeatureTypeDiscontinuity (PR #616)


Geo Domain team: Please change description as follows: Properties of discontinuities or discontiuity sets in rock according to ISO EN 14689.

I can take care of that here in the PR.

-
Reply to this email directly, view it on GitHub<https://github.com/bSI-InfraRoom/IFC-Specification/pull/616#issuecomment-1534183353>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALWNTMQ4UVZFNJKM3MOO6LDXENHR7ANCNFSM6AAAAAAXPD6JY4>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>

2023-05-04 07:59 UTC, larswik commented
> We further need to change the property names with abbreviation "disc"... to "discontinuity"..., for consistency

I will take care of that as well.

2023-12-03 17:55 UTC, SergejMuhic requested changes
For type https://github.com/bSI-InfraRoom/IFC-Specification/pull/600#pullrequestreview-1761310641

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityAperture_1$QA6RBqr9RARD6tIYf9PS/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityAperture_1QA6RBqr9RARD6tIYf9PS" Name="DiscontinuityAperture" UniqueId="7f68a19b-2f4d-496c-a6cd-1b74a2a4965c" Proper
Talks about one distance, how bounded value?

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63" Name="DiscontinuityFilling" UniqueId="325d8d6e-2038-41d1-8f21-80f3f0ef6183" Primary
`IfcPropertyReferenceValue` : `IfcMaterial`?

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityPersistence_2jSFfgBMbCJuC_pIPr2mIZ/Documentation.md
> +The linear extent of discontinuities from their inception to their termination in solid rock mass or against other discontinuities or outside the exposure shall be reported. The size of the exposure
Measurements made in three directions, how does this fit into one `IfcPositiveLengthMeasure`?

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityRoughness_3CM7$6yP532AGwtR4DvxEn/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityRoughness_3CM76yP532AGwtR4DvxEn" Name="DiscontinuityRoughness" UniqueId="cc587fc6-f191-4308-a43a-ddb10de7b3b1" Prim
Seems to be enum material.

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuitySpacing_2vj186oF501esx_J1YKnYO/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuitySpacing_2vj186oF501esx_J1YKnYO" Name="DiscontinuitySpacing" UniqueId="b9b41206-c8f1-4006-8dbb-f93062531898" Primary
`IfcText`?

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityStrikeDirection_2OgLQou3zDDO0kYsfjEdze/Documentation.md
> +The geographic  direction of a line created by the intersection of a plane and the horizontal plane. If non specific convention is used, this angular value is in the range 0 to 18 degrees. In this ca
How is this "an indication of the dip orientation (Quadrant)." information provided?

0-18 or 0-180 degrees?

```suggestion
The geographic direction of a line created by the intersection of a plane and the horizontal plane. If non specific convention is used, this angular value is in the range 0 to 18 degrees. In this case, there is an ambiguity on the dip orientation. For example, a plane with an orientation of 90 degrees from the north could either have a dip direction to the North or to the South. Thus, to avoid this ambiguity, a strike value is generally completed with an indication of the dip orientation (Quadrant).
```

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/d/DiscontinuityWaterPresence_13x1J$ipnCAAAJyT_0MNF4/Documentation.md
> +Descriptive of estimated waterinflow in excavation, to be used to define Jw(Barton), or RMR groudnwater inflow rating.
```suggestion
Description of estimated water inflow in excavation, to be used to define Jw(Barton), or RMR groundwater inflow rating.
```

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/r/RQD_2o32BT3ZX4bO$w85z$rZ25/Documentation.md
> +Quotient of the cumulative length of cores with a length greater than 10 cm, by the total length of the core pass with a length greater than or equal to 1m
```suggestion
Quotient of the cumulative length of cores with a length greater than 10 cm, by the total length of the core pass with a length greater than or equal to 1m.
```

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Properties/r/RQD_2o32BT3ZX4bO$w85z$rZ25/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="RQD_2o32BT3ZX4bOw85zrZ25" Name="RQD" UniqueId="b20c22dd-0e38-4495-8ffa-205f7fd63085" PrimaryDataType="IfcPositiveRatioMeasure" /
Cryptic name. Could we make it more descriptive?

2023-12-03 17:55 UTC, SergejMuhic commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_GeoScienceFeatureTypeDiscontinuity/Documentation.md
> +Properties of discontinuities or discontiuity sets in rock according to ISO EN 14689.
```suggestion
Properties of discontinuities or discontinuity sets in rock.
>NOTE according to ISO EN 14689
```

2023-12-07 09:27 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityAperture_1$QA6RBqr9RARD6tIYf9PS/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityAperture_1QA6RBqr9RARD6tIYf9PS" Name="DiscontinuityAperture" UniqueId="7f68a19b-2f4d-496c-a6cd-1b74a2a4965c" Proper
> Talks about one distance, how bounded value?

According to excel spec.

2023-12-07 09:30 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63" Name="DiscontinuityFilling" UniqueId="325d8d6e-2038-41d1-8f21-80f3f0ef6183" Primary
> `IfcPropertyReferenceValue` : `IfcMaterial`?

Would be ok to me. @j-weil.

2023-12-07 09:31 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityPersistence_2jSFfgBMbCJuC_pIPr2mIZ/Documentation.md
> +The linear extent of discontinuities from their inception to their termination in solid rock mass or against other discontinuities or outside the exposure shall be reported. The size of the exposure
> Measurements made in three directions, how does this fit into one `IfcPositiveLengthMeasure`?

Good question. @j-weil.

2023-12-07 09:32 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityRoughness_3CM7$6yP532AGwtR4DvxEn/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityRoughness_3CM76yP532AGwtR4DvxEn" Name="DiscontinuityRoughness" UniqueId="cc587fc6-f191-4308-a43a-ddb10de7b3b1" Prim
> Seems to be enum material.

Yes! @j-weil.

2023-12-07 09:33 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuitySpacing_2vj186oF501esx_J1YKnYO/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuitySpacing_2vj186oF501esx_J1YKnYO" Name="DiscontinuitySpacing" UniqueId="b9b41206-c8f1-4006-8dbb-f93062531898" Primary
> `IfcText`?

Looking at the examples (20-60mm, Extremely close) it looks like a label or text. IfcText according to excel spec.

2023-12-07 11:49 UTC, j-weil commented on IFC4x3/Properties/d/DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63" Name="DiscontinuityFilling" UniqueId="325d8d6e-2038-41d1-8f21-80f3f0ef6183" Primary
label is enough I would say, there will not be more properties directly related to this filling

2024-06-03 10:12 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityAperture_1$QA6RBqr9RARD6tIYf9PS/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityAperture_1QA6RBqr9RARD6tIYf9PS" Name="DiscontinuityAperture" UniqueId="7f68a19b-2f4d-496c-a6cd-1b74a2a4965c" Proper
Changed to single value.

2024-06-03 10:13 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityFilling_0oNOrk83X1qOyXWFFmxs63" Name="DiscontinuityFilling" UniqueId="325d8d6e-2038-41d1-8f21-80f3f0ef6183" Primary
IfcLabel from discussion with domain.

2024-06-03 10:13 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityPersistence_2jSFfgBMbCJuC_pIPr2mIZ/Documentation.md
> +The linear extent of discontinuities from their inception to their termination in solid rock mass or against other discontinuities or outside the exposure shall be reported. The size of the exposure
Reused property from Book A.

2024-06-03 10:14 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityRoughness_3CM7$6yP532AGwtR4DvxEn/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuityRoughness_3CM76yP532AGwtR4DvxEn" Name="DiscontinuityRoughness" UniqueId="cc587fc6-f191-4308-a43a-ddb10de7b3b1" Prim
Reused property from Book A.

2024-06-03 10:14 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuitySpacing_2vj186oF501esx_J1YKnYO/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="DiscontinuitySpacing_2vj186oF501esx_J1YKnYO" Name="DiscontinuitySpacing" UniqueId="b9b41206-c8f1-4006-8dbb-f93062531898" Primary
Reused property from Book A.

2024-06-03 10:15 UTC, larswik commented on IFC4x3/Properties/d/DiscontinuityStrikeDirection_2OgLQou3zDDO0kYsfjEdze/Documentation.md
> +The geographic  direction of a line created by the intersection of a plane and the horizontal plane. If non specific convention is used, this angular value is in the range 0 to 18 degrees. In this ca
Renamed to StrikeDirection with definition "The geographic direction of a line created by the intersection of a plane and the horizontal plane. If non specific convention is used, this angular value is in the range 0 to 180 degrees. A strike value is generally completed with an indication of the dip direction." and also added property DipDirection from Book A.

2024-06-03 10:16 UTC, larswik commented on IFC4x3/Properties/r/RQD_2o32BT3ZX4bO$w85z$rZ25/DocProperty.xml
> +<DocProperty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="RQD_2o32BT3ZX4bOw85zrZ25" Name="RQD" UniqueId="b20c22dd-0e38-4495-8ffa-205f7fd63085" PrimaryDataType="IfcPositiveRatioMeasure" /
Renamed to RockQualityDesignation.

2024-07-05 13:24 UTC, merged