CT Body Voxel geometry
bSI-InfraRoom/IFC-Specification pull request #617
Opened 2023-05-04 08:20 UTC by larswik

Partly fixes #524 (The CT part)

2023-05-04 08:24 UTC, pjanck requested changes
Can you please add the `RepresentationType` to the table [here](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/schema/ifcrepresentationresource/lexical/ifcshaperepresentation.htm) as well?

2023-05-04 08:27 UTC, larswik commented
> Can you please add the `RepresentationType` to the table [here](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/schema/ifcrepresentationresource/lexical/ifcshaperepresentation.htm) as well?

Will do!

2023-05-04 09:55 UTC, pjanck approved these changes
lftm

2023-05-11 15:16 UTC, SergejMuhic approved these changes

2023-05-21 19:34 UTC, merged