Deprecation of IFC 4.3 IfcGeotechnicalElement and subtypes
bSI-InfraRoom/IFC-Specification pull request #651
Opened 2023-06-05 09:13 UTC by larswik

Fixes #371

Please note that IfcBorehole is still used but was moved (subtype to IfcGeoScienceElement) in another PR.

2023-06-05 14:03 UTC, pjanck requested changes

2023-06-05 14:03 UTC, pjanck commented on IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcGeotechnicalStratumTypeEnum/Documentation.md
> +> DEPRECATION&nbsp; The entity _IfcGeotechnicalStratumTypeEnum_ shall not be used anymore due to deprecation of _IfcGeotechnicalStratum_, Instead use _IfcGeoScienceFeature_ including _IfcGeoScienceFe
```suggestion
> DEPRECATION&nbsp; The entity _IfcGeotechnicalStratumTypeEnum_ shall not be used anymore due to deprecation of _IfcGeotechnicalStratum_. Use _IfcGeoScienceFeature_ including _IfcGeoScienceFeatureTypeEnum_ instead.
```

2023-06-15 05:44 UTC, SergejMuhic approved these changes

2023-06-20 20:08 UTC, pjanck approved these changes
Great work!

2023-06-20 20:08 UTC, merged